# Generated by Django 3.1.6 on 2021-03-06 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pdf',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='co_convenor1',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phone_number1',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='co_convenor2',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='convenor',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='member1',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='member2',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone_number2',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone_number3',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='role1',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='role2',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='role3',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='role4',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='role5',
        ),
        migrations.RemoveField(
            model_name='event',
            name='pdf',
        ),
        migrations.RemoveField(
            model_name='event',
            name='venue',
        ),
        migrations.AddField(
            model_name='contact',
            name='role',
            field=models.CharField(choices=[('Converner', 'Converner'), ('Co_Converner1', 'Co_Converner1'), ('Co_Converner2', 'Co_Converner2'), ('Member1', 'Member1'), ('Member2', 'Member2')], default='test', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='rules_doc',
            field=models.FileField(blank=True, upload_to='rules'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EventContact', to='events.event'),
        ),
    ]
