# Generated by Django 3.1.6 on 2021-03-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210306_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='role',
            field=models.CharField(choices=[('Converner', 'Converner'), ('Co_Convener1', 'Co_Convener1'), ('Co_Convener2', 'Co_Convener2'), ('Member1', 'Member1'), ('Member2', 'Member2')], max_length=15),
        ),
    ]
