# Generated by Django 3.1.7 on 2021-03-07 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20210306_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='event',
            name='about',
        ),
    ]
