# Generated by Django 3.1.7 on 2021-03-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20210307_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Technical', 'Technical'), ('Gaming', 'Gaming'), ('Design and Photography', 'Design and Photography'), ('Literature', 'Literature')], default='Technical', max_length=30),
            preserve_default=False,
        ),
    ]
