# Generated by Django 3.1.7 on 2021-03-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_contact_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
