# Generated by Django 3.1.7 on 2021-03-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20210307_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='team_size',
            field=models.IntegerField(default=1),
        ),
    ]
