# Generated by Django 3.1.7 on 2021-03-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20210309_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='role',
            field=models.CharField(choices=[('Convenor', 'Convenor'), ('Co-Convenor1', 'Co_Convenor1'), ('Co-Convenor2', 'Co_Convenor2'), ('Member1', 'Member1'), ('Member2', 'Member2')], max_length=15),
        ),
    ]
