# Generated by Django 3.1.7 on 2021-03-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20210315_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('tech', 'Technical'), ('gaming', 'Gaming'), ('design-photo', 'Design and Photography'), ('lit', 'Literature')], max_length=30),
        ),
    ]
