# Generated by Django 3.1.7 on 2021-03-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0012_auto_20210315_1159"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="short_name",
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name="event",
            name="rules_doc",
            field=models.URLField(blank=True),
        ),
    ]
