# Generated by Django 3.1.7 on 2021-03-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20210318_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='social_media',
            field=models.URLField(blank=True, null=True),
        ),
    ]
