# Generated by Django 3.1.7 on 2021-03-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20210323_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
