# Generated by Django 3.1.6 on 2021-03-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='linkedIn',
        ),
        migrations.AddField(
            model_name='team',
            name='linked_in',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='team',
            name='portfolio',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='dribble',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='role',
            field=models.CharField(choices=[('lead', 'Lead'), ('co_lead', 'Co-Lead'), ('member', 'Member')], max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='team',
            field=models.CharField(choices=[('core', 'Core'), ('core_support', 'Core Support'), ('web_dev', 'Web Dev'), ('design', 'Design Team'), ('video_editing', 'Video Editing Team'), ('public_relations', 'P R Team'), ('gaming', 'Gaming')], max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='twitter',
            field=models.URLField(blank=True),
        ),
    ]
