# Generated by Django 3.1.6 on 2021-03-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20210306_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='role',
            field=models.CharField(choices=[('Lead', 'Lead'), ('co_lead', 'Co-Lead'), ('member', 'Member')], max_length=100),
        ),
    ]
