# Generated by Django 3.1.6 on 2021-03-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20210306_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='role',
            field=models.CharField(choices=[('Student Convener', 'Student Convenor'), ('Technical Lead', 'Technical Lead'), ('Convener', 'Convener'), ('Head', 'Head'), ('Co-Head', 'Co-Head'), ('Member', 'Member')], max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='team',
            field=models.CharField(choices=[('Core', 'Core'), ('Core Support', 'Core Support'), ('Development', 'Web Dev'), ('Design', 'Design'), ('Video Editing', 'Video Editing'), ('PR', 'PR'), ('Gaming', 'Gaming')], max_length=100),
        ),
    ]
