# Generated by Django 3.1.7 on 2021-03-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_auto_20210307_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='role',
            field=models.CharField(choices=[('President', 'President'), ('Student Convenor', 'Student Convenor'), ('Technical Lead', 'Technical Lead'), ('Technical Co-Lead', 'Technical Co-Lead'), ('Convenor', 'Convenor'), ('Head', 'Head'), ('Co-Head', 'Co-Head'), ('Member', 'Member')], max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='team',
            field=models.CharField(choices=[('core', 'Core'), ('core-support', 'Core Support'), ('web', 'Web Dev'), ('design', 'Design'), ('video-editing', 'Video Editing'), ('pr', 'PR'), ('gaming', 'Gaming')], max_length=100),
        ),
    ]
