# Generated by Django 3.1.7 on 2021-03-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_authtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='institute',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
