# Generated by Django 3.1.7 on 2021-03-09 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20210309_1700'),
        ('accounts', '0002_account_profile_pic'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_size', models.IntegerField(default=1)),
                ('is_full', models.BooleanField(default=False)),
                ('team_code', models.CharField(default=None, max_length=5)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_team', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_team', to='accounts.account')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='events.event')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_member', to='registration.teamstatus')),
            ],
        ),
    ]
