# Generated by Django 3.1.7 on 2021-03-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_teammember_teamstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamstatus',
            name='team_code',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
