# Generated by Django 3.1.7 on 2021-03-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20210318_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamstatus',
            name='team_code',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
